language: java
dist: trusty
jdk:
  - openjdk17

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "flaad-enterprises"
    token:
      secure:  ${SONAR_TOKEN}

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar -B