language: java
dist: trusty
jdk:
  - openjdk17

git:
  depth: false

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "flaad-enterprises"
    token: ${SONAR_TOKEN}

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
  - mvn sonar:sonar