info:
  app:
    name: Deep Stack API Client
    description: Set of API's that interacts with Deep Stack AI to determine if an images contains anything of interest.
    version: 1.0.0

spring:
  application:
    name: deepstack-api-client
  jackson:
    date-format: "dd-MM-yyyy hh:mm:ss"
    default-property-inclusion: use_defaults
    serialization:
      INDENT_OUTPUT: true
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      FAIL_ON_IGNORED_PROPERTIES: false


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
        followRedirects: true
  okhttp:
    enabled: true

logging:
  level:
    root: INFO
    org.flaad.deepstack.client: DEBUG


---

spring:
  config:
    activate:
      on-profile: dev

info:
  app:
    environment: dev

deepstack:
  api:
    name: deepstack
    url: http://192.168.1.118:11111
    path: /v1/vision/
    end-points:
      object-detection: /detection/
      face-detection: /face/
      scene-detection: /scene/

---

spring:
  config:
    activate:
      on-profile: prod

info:
  app:
    environment: prod

deepstack:
  api:
    name: deepstack
    url: http://192.168.1.118:11111
    path: /v1/vision/
